# Generated by Django 3.0 on 2020-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(default='pic/1.jpg', null=True, upload_to='pic'),
        ),
    ]
